name       : gweled
version    : 0.9.1
release    : 6
source     :
    - http://launchpad.net/gweled/trunk/0.9.1/+download/gweled-0.9.1.tar.gz : f6064989040949659f5a970cf3a9dd280615df7ad67c014ac37e1466ce91055d
license    : GPL-2.0-or-later
component  : games.puzzle
summary    : Gweled is a GNOME version of a popular game called Bejeweled or Diamond
    Mine.
description: |
    Gweled is a GNOME version of a popular PalmOS/Windows/Java game called Bejeweled or Diamond Mine.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libmikmod)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(sdl2)
setup      : |
    %patch -p0 < $pkgfiles/librsvg.patch

    %configure
build      : |
    %make
install    : |
    %make_install
    rm -Rf $installdir/var/games/*
